#!/bin/bash

cp /home/adman/.xinitrc /home/adman/prgm/configCat/xinitrc
cp /etc/vimrc /home/adman/prgm/configCat/vimrc
#basic vim settings kept in /etc/ for root use
cp /home/adman/.bashrc /home/adman/prgm/configCat/bashrc
cp /home/adman/.bash_profile /home/adman/prgm/configCat/bash_profile
#NNN enviroment variables mostly moved to /etc/enviroment. Only the pretty colors remain
cp /etc/environment /home/adman/prgm/configCat/enviroVar
#/etc/enviroment is used so that NNN will be configured when using as root
cp /home/adman/.config/feh/keys /home/adman/prgm/configCat/fehKeys
cp /home/adman/.config/apvlv/apvlvrc /home/adman/prgm/configCat/apvlvrc
cp /usr/share/applications/vim.desktop /home/adman/prgm/configCat/vimmy.desktop


